version: '3.4'

services:
  nesttypescriptstarter:
    image: nesttypescriptstarter
    build:
      context: services/auth
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3001:3001
